name: bench-excalidraw-avrea-cold
on:
  workflow_dispatch:
jobs:
  install:
    runs-on: avrea-ubuntu-latest-4-vcpu
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
